/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator.remastered;

import java.sql.Timestamp;

/**
 *
 * @author Adrian
 */
public class Main extends javax.swing.JFrame {
    Operations num = new Operations();
    /**
     * Creates new form Main
     */
    public Main() {
        System.out.println("Running status...");
        ServerConnection instance  = new ServerConnection();
        instance.ConnectionExchange();
        Consistency init = new Consistency();
        init.preservation();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtA = new javax.swing.JTextField();
        txtop = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtR)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtop, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtR, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double castA = Double.parseDouble(txtA.getText());
        String textop = txtop.getText();
        double castB = Double.parseDouble(txtB.getText());
        int id = (int) (Math.random()*100000);
        int puerto = (int) Math.floor(Math.random()*(2000-1000+1)+1000);
        Timestamp ts1 = new Timestamp(System.currentTimeMillis());  
        int val=ts1.hashCode(); 
        
            if("/".equals(textop)){
                txtR.setText(castA + " / " + castB + " Result:" + num.division(castA, castB)+ '\n' + "HASH: " + val + "\n" + "ID :" + id);
                System.out.println(castA + " / " + castB + " Result:" + num.division(castA, castB));
                System.out.println("HASH: " + val + "\n" + "ID :" + id);
                Division d = new Division();
                d.Divtext.setText(txtR.getText());
                d.setVisible(true);
            }
            else if("*".equals(textop)){
                txtR.setText(castA + " * " + castB +" Result:" + num.multiplication(castA, castB)+ '\n' + "HASH: " + val + "\n" + "ID :" + id);
                System.out.println(castA + " * " + castB +" Result:" + num.multiplication(castA, castB));
                System.out.println("HASH: " + val + "\n" + "ID :" + id);
                Multiplication m = new Multiplication();
                m.Multext.setText(txtR.getText());
                m.setVisible(true);
            }
            else if("+".equals(textop)){
                txtR.setText(castA + " + " + castB +" Result:" + num.addition(castA, castB)+ '\n' + "HASH: " + val + "\n" + "ID :" + id);
                System.out.println(castA + " + " + castB +" Result:" + num.addition(castA, castB));
                System.out.println("HASH: " + val + "\n" + "ID :" + id);
                Addition a = new Addition();
                a.Addtext.setText(txtR.getText());
                a.setVisible(true); 
            }
            else if("-".equals(textop)){
                txtR.setText(castA + " - " + castB +" Result:" + num.sustraction(castA, castB)+ '\n' + "HASH: " + val + "\n" + "ID :" + id);
                System.out.println(castA + " - " + castB +" Result:" + num.sustraction(castA, castB));
                System.out.println("HASH: " + val + "\n" + "ID :" + id);
                Sustraction s = new Sustraction();
                s.Sustext.setText(txtR.getText());
                s.setVisible(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtop;
    // End of variables declaration//GEN-END:variables
}
